version: '3'

services:
  postgres:
    image: 'postgres:latest'
    container_name: 'java-postgres'
    ports:
      - "5433:5432"
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_HOST_AUTH_METHOD=trust'
      - 'POSTGRES_DB=java'