spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: root1234
    driver-class-name: org.postgresql.Driver
  jpa:
    properties.hibernate:
      batch_size: 50
      fetch_size: 50
      show_sql: true
      format_sql: true
      hbm2ddl.auto: validate
    open-in-view: false
okta:
  oauth2:
    issuer: https://dev-n26fsmmx8g0s2f8e.us.auth0.com/
    client-id: NIrdk00WUQOTOg7y66vZ8txZoqLmHcoT
    client-secret: NsIM_sMh3TpDrW5FtJCRhJ5EcJhzS_TKyzSTTbyfAS5mIm4L1LqrNIWc6K78qD4f