spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://agroex-db.cn2eswsyegkf.us-east-1.rds.amazonaws.com:5432/api_t3}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:agroex-123}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties.hibernate:
      batch_size: 50
      fetch_size: 50
      show_sql: true
      format_sql: true
      hbm2ddl.auto: update
    open-in-view: false
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_pVgpqPThD/.well-known/jwks.json
          issuer-uri: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_pVgpqPThD
aws:
  accessKey: AKIAXYKJRCXIYC3CQZUQ
  secretAccessKey: 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
  bucketName: ita-labs-2024-t3
app:
  scheduler:
    interval: 20s