spring:
  mvc:
    format:
      date: iso
    view:
      suffix: .html
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: root1234
    driver-class-name: org.postgresql.Driver
  jpa:
    properties.hibernate:
      batch_size: 50
      fetch_size: 50
      show_sql: true
      format_sql: true
      hbm2ddl.auto: update
    open-in-view: false
