# This workflow will apply a label to a newly created issue and assign it to a project.
#
# To use this workflow, you will need to set up a .github/labeler.yml
# file with configuration.  For more information, see:
# https://github.com/actions/labeler

name: Auto Label and Add to Project
on:
  issues:
    types: [opened]

jobs:
  auto-label-and-add-to-project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Добавить метку "API"
        uses: actions/add-labels@v2
        with:
          labels: "API"

      - name: Добавить в проект "ITA-Labs-2024-T3"
        uses: srggrs/assign-one-project-github-action@v1.0.0
        with:
          project_id: 1
          add_to_column: "Todo"
